INSERT INTO CAULDRON (CAPACITY, WATERTEMPERATURE, HELLFLOOR) VALUES (5, 75, 3);
INSERT INTO CAULDRON (CAPACITY, WATERTEMPERATURE, HELLFLOOR) VALUES (2, 30, 1);
INSERT INTO SINNER (FIRSTNAME, LASTNAME, SIN, RELEASEDATE, SIGNEDCONTRACT, CAULDRONID) VALUES
          ('Joe', 'Doe', 'Murder', '2020-04-01', FALSE, 1);
INSERT INTO SINNER (FIRSTNAME, LASTNAME, SIN, RELEASEDATE, SIGNEDCONTRACT, CAULDRONID) VALUES
          ('Jack', 'Black', 'Murder', NULL, TRUE, 1);